import React from 'react';
import MoviesRow from './MoviesRow'; 

function MainPage() {
  const categories = [
    { title: '', shows: [{ id: 0, title: 'The Boy Who Became the best at the magic academy', url: 'https://www.youtube.com/embed/sXWFr5Nk-g8' }, { id: 1, title: 'He Was Born As A Weak Goblin But Soon Became The Strongest Being In This World ', url: 'https://www.youtube.com/embed/cHsYClnlZEM?si' }, { id: 2, title: 'Demon Erased Memory', url: 'https://www.youtube.com/embed/ABG0BthfTOQ?si'}, { id: 3, title: 'OverWatch', url: 'https://www.youtube.com/embed/PI-iFfhRKEc?si'}, { id: 4, title: 'Blue Eye Samurai', url: 'https://www.youtube.com/embed/Cm73ma6Ibcs?si'}, { id: 5, title: 'Invincible Magic Power Episode 1-12', url: 'https://www.youtube.com/embed/1ZKUrxj2-Cc?si'}, { id: 6, title: 'Blades Of The Guardians Episode 1-12', url: 'https://www.youtube.com/embed/VBKXLvGjH_w?si'}, { id: 7, title: 'Silent Voice', url: 'https://www.youtube.com/embed/hbuZrg1ZAnE?si'}, ] },  
    { title: '', shows: [{ id: 0, title: 'New Anime Movie Eng Dub 2023', url: 'https://www.youtube.com/embed/zkYN0MI9nZI?si=rRFKJIkYOLZoq6X1' }, { id: 1, title: 'Fairy Tail The Movie: Phoenix Priestess', url: 'https://www.youtube.com/embed/HVjQp54UboA?si=KapIbxwLJEaA4sQo' }, { id: 2, title: 'School With The Revival Of A Legend Episode 1-24', url: 'https://www.youtube.com/embed/GIhh-HitJTk?si=tnxVCTdnN5LQ78dQ' }, { id: 3, title: 'Blade Of The Phantom Master', url: 'https://www.youtube.com/embed/htvqAezZMyo?si'  }, { id: 4, title: 'Whos Left Behind', url: 'https://www.youtube.com/embed/zQjuqyf87Yo?si'},{ id: 5, title: 'The Secret World Of Arrietty', url: 'https://www.youtube.com/embed/j5YmuKe6Ouo?si'}, { id: 6, title: 'Demon Spirit', url: 'https://www.youtube.com/embed/KqR1RE9hWoc?si'},{ id: 7, title: 'God Of Lightning', url: 'https://www.youtube.com/embed/JnNv7Ao39JI?si'}, ] },
    { title: '', shows: [{ id: 0, title: 'Demon Slayer: Kimetsu no Yaiba The Hinokami Chronicles', url: 'https://www.youtube.com/embed/GCJnG6DYEeg?si=FJ0eZj2r81j1Y4Ww' }, { id: 1, title: 'The Aritocrats Otherwordly Adenture: Serving Gods Who Go To Far Full Series Episodes 1-12', url: 'https://www.youtube.com/embed/ZrKCfj3u2cs?si'}, { id: 2, title: 'Chainsaw Man', url: 'https://www.youtube.com/embed/Bzq8piNiZpE?si' }, { id: 3, title: 'Samurai Reckoning: The Isekai Chronicles', url: 'https://www.youtube.com/embed/u3Y-bqUqpXU?siç'}, { id: 4, title: 'Mysterious Veteran Of The Royal Empire Episodes 1-13', url: 'https://www.youtube.com/embed/jzj5IW1lud8?si'}, { id: 5, title: 'Rage Of Bahamut: Genesis', url: 'https://www.youtube.com/embed/2TXh7dROnac?si',}, { id: 6, title: 'Blazblue Alter Memory Episodes 1-12', url: 'https://www.youtube.com/embed/ObCwd2bL8DU?si'}, { id: 7, title: 'Demon Erased Memory', url: 'https://www.youtube.com/embed/ABG0BthfTOQ?si'}] }, 
    { title: '', shows: [{ id: 0, title: 'Black Fox Movie', url: 'https://www.youtube.com/embed/AiESdN5SC8s?si=Bdc7UF_0siSfA3ee' }, { id: 1, title: 'Hello World Sci-fi Movie', url: 'https://www.youtube.com/embed/EgrehrOCpcA?si' }, { id: 2, title: 'Dororo Episodes 1-24', url: 'https://www.youtube.com/embed/NF7xiEKZqO0?si'}, { id: 3, title: 'Sono Gish Zubbe D Member Episode Season 1-12', url: 'https://www.youtube.com/embed/Ajb66E_mGjw?si'}, { id: 4, title: 'Twilight', url: 'https://www.youtube.com/embed/trExdyeD01E?si'}, { id: 5, title: 'Orange', url: 'https://www.youtube.com/embed/GHiosL7ZLz8?'}, { id: 6, title: 'Demon Kid', url: 'https://www.youtube.com/embed/GFzHQCzvRu8?si'}, { id: 7, title: 'Attack On Titan Chronicles', url: 'https://www.youtube.com/embed/Gg9aeloyWZU?si'}, ]}, 
    { title: '', shows: [{ id: 0, title: 'Top 1 Ninja Smash Demons Episodes 1-12', url: 'https://www.youtube.com/embed/5h0L68KEdxc?si=pMzXt_FZJdyngpa3' }, { id: 1, title: 'Black Brothers Full Movie', url: 'https://www.youtube.com/embed/oxhDB2GYlY4?si'}, { id: 2, title: 'Dragon Ball Super 3', url: 'https://www.youtube.com/embed/oTZS3yuLcqY?si'}, { id: 3, title: 'Sono Gish Zubbe D Member Episode Season 1-12', url: 'https://www.youtube.com/embed/Ajb66E_mGjw?si'},{ id: 4, title: 'Everyday Life In Another World Episodes 1-12', url: 'https://www.youtube.com/embed/5laTzUqY-V4?si'}, { id: 5, title: 'Hero From The Past Episode 1-13 War On Geminar', url: 'https://www.youtube.com/embed/fnJZfkQDarw?si'}, { id: 6, title: 'Unlimited Swordworks', url: 'https://www.youtube.com/embed/eVAd_S-7X-Y?si'}, { id: 7, title: 'Code Breaker', url: 'https://www.youtube.com/embed/xYXx-rR2s-w?si'}, ]}
    // Add more categories as needed
  ];
 
  return (
    <div style={{ backgroundColor: 'black', color: 'white'}}>
      {categories.map((category , index) => (
        <MoviesRow id={index} key={index} title={category.title} shows={category.shows} />
      ))}
    </div>
  );
}
 
export default MainPage;